server:
  port : 8080

fint:
  kafka:
    application-id: consumer
    enable-ssl: false
    default-replicas: 1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer
  webflux:
    base-path: /consumer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
